import Library
import random
# This is an internal testing program to test the functionality of the Library program

def populate_test_library(num_books=100):
    """Adds a specified number of test books to the library."""
    titles = [
        "The Hitchhiker's Guide to the Galaxy",
        "Pride and Prejudice",
        "1984",
        "To Kill a Mockingbird",
        "The Lord of the Rings",
        "The Great Gatsby",
        "One Hundred Years of Solitude",
        "The Catcher in the Rye",
        "Moby Dick",
        "Crime and Punishment",
        "War and Peace",
        "The Odyssey",
        "Alice's Adventures in Wonderland",
        "The Adventures of Sherlock Holmes",
        "Don Quixote",
        "The Handmaid's Tale",
        "Brave New World",
        "The Metamorphosis",
        "Dune",
        "The Book Thief",
        "The Adventures of Huckleberry Finn",
        "Les Misérables",
        "The Count of Monte Cristo",
        "Jane Eyre",
        "Frankenstein",
        "The Adventures of Tom Sawyer",
        "The Picture of Dorian Gray",
        "The Three Musketeers",
        "Treasure Island",
        "Dracula",
        "The Time Machine",
        "The War of the Worlds",
        "The Invisible Man",
        "The Strange Case of Dr. Jekyll and Mr. Hyde",
        "The Wind in the Willows",
        "The Secret Garden",
        "The Call of the Wild",
        "Peter Pan",
        "Anne of Green Gables",
        "The Lion, the Witch and the Wardrobe",
        "The Hobbit",
        "The Little Prince",
        "The Alchemist",
        "The Da Vinci Code",
        "Harry Potter and the Philosopher's Stone",
        "The Hunger Games",
        "The Girl with the Dragon Tattoo",
        "Fifty Shades of Grey",
        "Gone Girl",
        "The Martian",
        "Ready Player One",
        "A Game of Thrones",
        "The Silent Patient",
        "Where the Crawdads Sing",
        "The Midnight Library",
        "Normal People" ,
        "The Godfather",
        "The Lord of the Flies",
        "The Picture of Dorian Gray",
        "The Wind in the Willows",
        "The Secret Garden",
        "The Call of the Wild",
        "Peter Pan",
        "Anne of Green Gables",
        "The Lion, the Witch and the Wardrobe",
        "The Little Prince",
        "The Alchemist",
        "The Da Vinci Code",
        "Harry Potter and the Goblet of Fire",
        "The Hunger Games: Catching Fire",
        "The Girl Who Played with Fire",
        "Fifty Shades Darker",
        "Gone Girl",
        "The Martian",
        "Artemis",
        "A Court of Thorns and Roses",
        "Red, White & Royal Blue",
        "Circe",
        "Six of Crows",
        "The Song of Achilles",
        "The Invisible Life of Addie LaRue",
        "The Love Hypothesis",
        "From Blood and Ash",
        "A Good Girl's Guide to Murder",
        "They Both Die at the End",
        "The Seven Husbands of Evelyn Hugo",
        "It Ends with Us",
        "The Guest List",
        "Verity",
        "The House in the Cerulean Sea",
        "The Invisible Life of Addie LaRue",
        "The Midnight Library",
        "Project Hail Mary",
        "The Paris Apartment",
        "Reminders of Him",
        "The House Across the Lake",
        "The Last Thing He Told Me",
        "It Starts with Us",
        "Run, Rose, Run",
        "The Thursday Murder Club",
        "The Bullet That Missed",
        "The Love Hypothesis",
        "The Paris Apartment",
        "The House in the Cerulean Sea"
    ]

    authors = [
        "Douglas Adams",
        "Jane Austen",
        "George Orwell",
        "Harper Lee",
        "J.R.R. Tolkien",
        "F. Scott Fitzgerald",
        "Gabriel Garcia Marquez",
        "J.D. Salinger",
        "Herman Melville",
        "Fyodor Dostoevsky",
        "Leo Tolstoy",
        "Homer",
        "Lewis Carroll",
        "Arthur Conan Doyle",
        "Miguel de Cervantes",
        "Margaret Atwood",
        "Aldous Huxley",
        "Franz Kafka",
        "Frank Herbert",
        "Markus Zusak",
        "Mark Twain",
        "Victor Hugo",
        "Alexandre Dumas",
        "Charlotte Brontë",
        "Mary Shelley",
        "Mark Twain",
        "Oscar Wilde",
        "Alexandre Dumas",
        "Robert Louis Stevenson",
        "Bram Stoker",
        "H.G. Wells",
        "H.G. Wells",
        "H.G. Wells",
        "Robert Louis Stevenson",
        "Kenneth Grahame",
        "Frances Hodgson Burnett",
        "Jack London",
        "J.M. Barrie",
        "L.M. Montgomery",
        "C.S. Lewis",
        "J.R.R. Tolkien",
        "Antoine de Saint-Exupéry",
        "Paulo Coelho",
        "Dan Brown",
        "J.K. Rowling",
        "Suzanne Collins",
        "Stieg Larsson",
        "E L James",
        "Gillian Flynn",
        "Andy Weir",
        "Ernest Cline",
        "George R.R. Martin",
        "Alex Michaelides",
        "Delia Owens",
        "Matt Haig",
        "Sally Rooney",
        "Mario Puzo",
        "William Golding",
        "Oscar Wilde",
        "Kenneth Grahame",
        "Frances Hodgson Burnett",
        "Jack London",
        "J.M. Barrie",
        "L.M. Montgomery",
        "C.S. Lewis",
        "Antoine de Saint-Exupéry",
        "Paulo Coelho",
        "Dan Brown",
        "J.K. Rowling",
        "Suzanne Collins",
        "Stieg Larsson",
        "E L James",
        "Gillian Flynn",
        "Andy Weir",
        "Andy Weir",
        "Sarah J. Maas",
        "Casey McQuiston",
        "Madeline Miller",
        "Leigh Bardugo",
        "Madeline Miller",
        "V.E. Schwab",
        "Ali Hazelwood",
        "Jennifer L. Armentrout",
        "Holly Jackson",
        "Adam Silvera",
        "Taylor Jenkins Reid",
        "Colleen Hoover",
        "Lucy Foley",
        "Colleen Hoover",
        "T.J. Klune",
        "V.E. Schwab",
        "Matt Haig",
        "Andy Weir",
        "Lucy Foley",
        "Colleen Hoover",
        "Riley Sager",
        "Laura Dave",
        "Colleen Hoover",
        "Dolly Parton and James Patterson",
        "Richard Osman",
        "Richard Osman",
        "Ali Hazelwood",
        "Lucy Foley",
        "T.J. Klune"
    ]

    for i in range(num_books):
        title = random.choice(titles)
        author = authors[titles.index(title)] # ensure correct author for each title
        isbn = f"978-0-{random.randint(100000000, 999999999)}"  # Generate random ISBN
        count = random.randint(1, 10)  # Random number of copies (1-5)
        Library.add_book_to_library(title, author, isbn, count)

# Call the function to populate your library with 20 test books
populate_test_library()

Library.library_main_menu()



